import { HttpStatus } from "@nestjs/common";

export enum POSTGRES_ERROR_CODES {
// Class 22 — Data Exception
  INVALID_TEXT_REPRESENTATION = '22P02', // e.g. invalid input syntax for type UUID
  NUMERIC_VALUE_OUT_OF_RANGE = '22003',
  STRING_DATA_RIGHT_TRUNCATION = '22001',
  DIVISION_BY_ZERO = '22012',
  DATETIME_FIELD_OVERFLOW = '22008',

  // Class 23 — Integrity Constraint Violation
  UNIQUE_VIOLATION = '23505',
  FOREIGN_KEY_VIOLATION = '23503',
  NOT_NULL_VIOLATION = '23502',
  CHECK_VIOLATION = '23514',

  // Class 40 — Transaction Rollback
  SERIALIZATION_FAILURE = '40001',
  DEADLOCK_DETECTED = '40P01',

  // Class 42 — Syntax Error or Access Rule Violation
  SYNTAX_ERROR = '42601',
  INSUFFICIENT_PRIVILEGE = '42501',
  UNDEFINED_TABLE = '42P01',
  UNDEFINED_COLUMN = '42703',

}
export const POSTGRES_ERROR_HTTP_STATUS: Record<string, HttpStatus> = {
  // Data exceptions → Bad Request
  [POSTGRES_ERROR_CODES.INVALID_TEXT_REPRESENTATION]: HttpStatus.BAD_REQUEST,
  [POSTGRES_ERROR_CODES.NUMERIC_VALUE_OUT_OF_RANGE]: HttpStatus.BAD_REQUEST,
  [POSTGRES_ERROR_CODES.STRING_DATA_RIGHT_TRUNCATION]: HttpStatus.BAD_REQUEST,
  [POSTGRES_ERROR_CODES.DIVISION_BY_ZERO]: HttpStatus.BAD_REQUEST,
  [POSTGRES_ERROR_CODES.DATETIME_FIELD_OVERFLOW]: HttpStatus.BAD_REQUEST,

  // Constraint violations
  [POSTGRES_ERROR_CODES.UNIQUE_VIOLATION]: HttpStatus.CONFLICT,
  [POSTGRES_ERROR_CODES.FOREIGN_KEY_VIOLATION]: HttpStatus.BAD_REQUEST, // hoặc 409 nếu business rule
  [POSTGRES_ERROR_CODES.NOT_NULL_VIOLATION]: HttpStatus.BAD_REQUEST,
  [POSTGRES_ERROR_CODES.CHECK_VIOLATION]: HttpStatus.BAD_REQUEST,

  // Transaction / Deadlock
  [POSTGRES_ERROR_CODES.SERIALIZATION_FAILURE]: HttpStatus.CONFLICT,
  [POSTGRES_ERROR_CODES.DEADLOCK_DETECTED]: HttpStatus.CONFLICT,

  // Syntax / Access
  [POSTGRES_ERROR_CODES.SYNTAX_ERROR]: HttpStatus.BAD_REQUEST,
  [POSTGRES_ERROR_CODES.INSUFFICIENT_PRIVILEGE]: HttpStatus.FORBIDDEN,
  [POSTGRES_ERROR_CODES.UNDEFINED_TABLE]: HttpStatus.BAD_REQUEST,
  [POSTGRES_ERROR_CODES.UNDEFINED_COLUMN]: HttpStatus.BAD_REQUEST,
};
export enum PricingType {
    NORMAL = 'NORMAL',
    FLASH_SALE = 'FLASH_SALE',
}