@dotenv = .env.development
@baseUrl = http://localhost:{{$dotenv PORT}}
@ContentType = application/json

@token = {{$dotenv TOKEN}}
### Get User Admin
# POST {{baseUrl}}/user-admin
GET {{baseUrl}}/user-admin?page=1&limit=100
Content-Type: {{ContentType}}
Authorization: Bearer {{token}} 

{
  "name": "user",
  "email": "sangdv219@gmail.com",
  "password": "123456",
  "gender": "Nam",
  "age": 22,
  "phone": "0919 528 956",
  "is_root": true,
  "is_active": true,
  "avatar": "abc"
}